### ISSUE TITLE
"Edit this page on GitHub" links are broken on online documentation

### ISSUE THREAD

**Issue by thomastoye** [slick/doc#3]
Steps for reproduction:
- Go to [a random page on the online documentation](http://slick.typesafe.com/doc/3.0.0/schemas.html)
- Click _Edit this page on GitHub_ (at the very top of the page)
- You now see a 404

An example link this takes you to is https://github.com/slick/slick/edit/master/src/sphinx/schemas.rst
This should take you to https://github.com/slick/slick/blob/master/slick/src/sphinx/schemas.rst https://github.com/slick/slick/edit/master/slick/src/sphinx/schemas.rst , I'm guessing

**Comment by the-Arioch** [comment]
Broken again, re-open it!
